$("#challenge5vars").append(`
  <table>
    <tr>
      <th>myInt:</th>
      <td></td>
    </tr>
    <tr>
      <th>myString:</th>
      <td></td>
    </tr>
    <tr>
      <th>myNumString:</th>
      <td></td></tr>
  </table>`);
$("#challenge5predictions").append(`
  <table>
    <tr>
      <th><b>Addition</b</th>
      <td></td>
    </tr>
    <tr>
      <th>myInt+myInt?</th>
      <td></td>
    </tr>
    <tr>
      <th>myInt+myString?</th>
      <td></td>
    </tr>
    <tr>
      <th>myInt+myNumString?</th>
      <td></td>
    </tr>
    <tr>
      <th>myNumString+myInt?</th>
      <td></td>
    </tr>
    <tr>
      <th><b>Fancier addition</b></th>
      <td></td>
    </tr>
    <tr>
      <th>myInt+myNumString+myString?</th>
      <td></td>
    </tr>
    <tr>
      <th>myInt+myInt+myString?</th>
      <td></td>
    </tr>
     <tr>
      <th>myString+myInt+myInt?</th>
      <td></td>
    </tr>
    <tr>
      <th><b>Subtraction</b></th>
      <td></td>
    </tr>
    <tr>
      <th>myInt-myString?</th>
      <td></td>
    </tr>
   <tr>
      <th>myInt-myNumString?</th>
      <td></td>
  </tr>
   <tr>
      <th>myString-myNumString</th>
      <td></td>
  </tr>
   <tr>
      <th><b>Comparisons</b></th>
      <td></td>
  </tr>
   <tr>
      <th>myInt==myNumString?</th>
      <td></td>
  </tr>
  <tr>
       <th>myInt===myNumString</th>
       <td></td>
  </tr>   
  </table>`);
