$("#challenge5vars").append(`
  <table>
    <tr>
      <th>myInt:</th>
      <td></td>
    </tr>
    <tr>
      <th>myString:</th>
      <td></td>
    </tr>
    <tr>
      <th>myNumString:</th>
      <td></td></tr>
  </table>`);
$("#challenge5predictions").append(`
  <table>
    <tr>
      <th></th>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
    </tr>
    <tr>
      <th></th>
      <td></td>
    </tr>
  </table>`);
